using Microsoft.Extensions.Logging;
using Siemens.Engineering.SW.Tags;
using System;

namespace TiaMcpServer.Siemens
{
    /// <summary>
    /// Creates tags and user constants in a tag table.
    /// </summary>
    /// <remarks>
    /// The half of the tag tables that did not exist. They have been exported since the snapshot
    /// was written, and until now nothing could author one — so a program generated by this server
    /// could refer to tags only if a person had typed them into TIA Portal first, which is half a
    /// program.
    ///
    /// **Nothing here overwrites.** An entry whose name is taken by an identical entry is reported
    /// as already there, which is the idempotence the repository requires; an entry whose name is
    /// taken by a *different* one is refused with both spellings named. Silently changing the type
    /// or the address of a tag the program already uses would compile and then behave differently,
    /// which is the worst outcome available.
    /// </remarks>
    public sealed class TagTableBuilder
    {
        private readonly ILogger? _logger;

        /// <summary>Creates a tag table builder.</summary>
        /// <param name="logger">Optional logger.</param>
        public TagTableBuilder(ILogger? logger = null)
        {
            _logger = logger;
        }

        /// <summary>Creates a tag, or reports the identical one that is already there.</summary>
        /// <param name="table">The table to create it in.</param>
        /// <param name="definition">Name, data type and logical address.</param>
        /// <returns>The tag as the project holds it, read back rather than echoed.</returns>
        /// <exception cref="PortalException">
        /// The name is taken by something different, or TIA Portal refused the type or the address.
        /// </exception>
        public TagInfo CreateTag(PlcTagTable table, TagDefinition definition)
        {
            RequireArguments(table, definition);
            RequireNameFree(table, definition, TagInfo.TagKind);

            var existing = table.Tags.Find(definition.Name);
            if (existing != null)
            {
                return RequireSame(TagTableReader.Describe(existing), definition);
            }

            var created = Create(
                () => table.Tags.Create(definition.Name, definition.DataTypeName, definition.Assignment),
                definition);

            _logger?.LogInformation("Tag {Tag} created in {Table}", definition.Name, table.Name);

            return TagTableReader.Describe(created);
        }

        /// <summary>Creates a user constant, or reports the identical one that is already there.</summary>
        /// <param name="table">The table to create it in.</param>
        /// <param name="definition">Name, data type and value.</param>
        /// <returns>The constant as the project holds it, read back rather than echoed.</returns>
        /// <exception cref="PortalException">
        /// The name is taken by something different, or TIA Portal refused the type or the value.
        /// </exception>
        public TagInfo CreateConstant(PlcTagTable table, TagDefinition definition)
        {
            RequireArguments(table, definition);
            RequireNameFree(table, definition, TagInfo.ConstantKind);

            var existing = table.UserConstants.Find(definition.Name);
            if (existing != null)
            {
                return RequireSame(TagTableReader.Describe(existing), definition);
            }

            var created = Create(
                () => table.UserConstants.Create(definition.Name, definition.DataTypeName, definition.Assignment),
                definition);

            _logger?.LogInformation("Constant {Constant} created in {Table}", definition.Name, table.Name);

            return TagTableReader.Describe(created);
        }

        private static void RequireArguments(PlcTagTable table, TagDefinition definition)
        {
            if (table == null || definition == null)
            {
                throw new PortalException(PortalErrorCode.InvalidParams, "table and definition are required");
            }
        }

        /// <remarks>
        /// Tags and constants share one namespace, so a tag cannot take the name of a constant even
        /// though they live in different compositions. Openness reports that collision as a generic
        /// failure, and a caller told only "creation failed" would look at the data type.
        /// </remarks>
        private static void RequireNameFree(PlcTagTable table, TagDefinition definition, string wanted)
        {
            var kind = OccupantKind(table, definition.Name);

            if (kind == null || kind == wanted)
            {
                return;
            }

            throw new PortalException(
                PortalErrorCode.InvalidState,
                $"'{definition.Name}' already names a {kind?.ToLowerInvariant()} in '{table.Name}'. " +
                "Tags and constants share one namespace, so the name has to be free of both.");
        }

        /// <remarks>
        /// The name is taken by something that is not what was asked for. Reporting the difference
        /// rather than the collision is what tells the caller whether it has a real conflict or a
        /// repeated call: a repeated call is the same in every field, and succeeds.
        /// </remarks>
        private static TagInfo RequireSame(TagInfo existing, TagDefinition definition)
        {
            var sameType = string.Equals(existing.DataTypeName, definition.DataTypeName, StringComparison.OrdinalIgnoreCase);
            var sameAssignment = string.Equals(existing.Assignment, definition.Assignment, StringComparison.OrdinalIgnoreCase);

            if (sameType && sameAssignment)
            {
                return existing;
            }

            throw new PortalException(
                PortalErrorCode.InvalidState,
                $"'{definition.Name}' already exists as {existing.DataTypeName} at '{existing.Assignment}', " +
                $"and this asks for {definition.DataTypeName} at '{definition.Assignment}'. " +
                "Nothing here overwrites: delete it in TIA Portal, or use another name.");
        }

        private static string? OccupantKind(PlcTagTable table, string name)
        {
            if (table.Tags.Find(name) != null)
            {
                return TagInfo.TagKind;
            }

            return table.UserConstants.Find(name) != null ? TagInfo.ConstantKind : null;
        }

        /// <remarks>
        /// A refused type, address or value is the caller's mistake, so it comes back as invalid
        /// input. Openness says only that creation failed, so its message is carried through: it is
        /// the only thing that distinguishes a bad data type from a bad address.
        /// </remarks>
        private static TCreated Create<TCreated>(Func<TCreated> create, TagDefinition definition)
        {
            try
            {
                return create();
            }
            catch (Exception failure)
            {
                throw new PortalException(
                    PortalErrorCode.InvalidParams,
                    $"TIA Portal refused '{definition.Name}' as {definition.DataTypeName} " +
                    $"at '{definition.Assignment}': {failure.Message}",
                    null,
                    failure);
            }
        }
    }
}
